### PR TITLE
Bugfix: Fix IconName type safety

### PR DESCRIPTION
**Pull request by tayambamwanza**
I removed the 'string' type from the name input, it turns out that it was actually preventing the autocomplete, because you could put any string inside, with this change, there will now be an autocomplete that shows only the icons that are supported by the library, as well as warning if you use an icon name that does not exist.

Image to demo, the working autocomplete, feel free to test it out. (I was working on another project for a while, came back to my own and only noticed this problem now)

Screenshot from 2021-09-14 17-54-29

### CODE REVIEW

**Comment by tayambamwanza** [comment]
In the image, I removed the exclamation mark temporarily just to show the demo as typescript wouldn't allow me to preset a value while the exclamation was there.

You'll see that the exclamation mark is back in the pr.

**Comment by avmaisak** [comment]
@tayambamwanza  - this repository has man branch as develop. The master branch is "stable". Please, rebase to the latest develop

**Comment by tayambamwanza** [comment]
@avmaisak I've never used rebase before, is ti fine if I just open a new pr?

**Comment by tayambamwanza** [comment]
Alright I think it will be easier to start over since it's a quick change, let me try again.

**Pull request closed without merging**
